# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  slack: circleci/slack@4.1
slack-fail-post-step: &slack-fail-post-step
  context:
    - swing-cypress-ui-api-slack
  post-steps:
    - slack/notify:
        branch_pattern: .+
        event: fail
        template: basic_fail_1
        channel: C03SQRV07R8
        
jobs:
  cypress-tests:

    docker:
      - image: cimg/base:2021.04

    steps:
    
      - checkout
      
      
      - restore_cache:
          key: v1-deps-{{ checksum "package.json" }}
      - run:
          name: Install Node.js
          command: |
            cd ~
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      # install dependencies
      - run:
          name: install dependencies
          command: |
              cd TLS_E2E_Automation 
              npm install
      - save_cache:
          key: v1-deps-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Install Cypress 
          command: |
            pwd
            cd TLS_E2E_Automation
            npm add cypress --dev
            npm add -D cypress-wait-until
            npm add -D faker 
      - run:
          name: Run Cypress tests
          command: |
            pwd
            cd TLS_E2E_Automation
            pwd
            npx cypress run  --env ENV=dev --spec 'cypress/e2e/PERFORMANCE/Perfromance.cy.js'


      - store_artifacts:
          path: cypress/screenshots
        
          
workflows:
  tests:
    jobs:
      - cypress-tests
        








