# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello

version: 2.1
orbs:
  slack: circleci/slack@4.1
slack-fail-post-step: &slack-fail-post-step
  context:
    - swing-cypress-ui-api-slack
  post-steps:
    - slack/notify:
        branch_pattern: .+
        event: fail
        template: basic_fail_1
        channel: C039YF77KMY
jobs:
  cypress-tests:
    working_directory: ~/project
    machine: true
    resource_class: nukengprod/pubsys-circleci-runner-dev
    parallelism: 2
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package.json" }}
      # install dependencies
      - run:
          name: install dependencies
          command: npm install
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run Cypress tests
          command: |
            npx cypress run  --spec "$( circleci tests glob cypress/integration/*.feature | circleci tests split --split-by=filesize | paste -sd "," -)"
      - store_artifacts:
          path: cypress/screenshots
workflows:
  tests:
    jobs:
      - cypress-tests:
          <<: *slack-fail-post-step
          filters:
            branches:
              only: main








